name = "clawmail"
main = "src/index.ts"
compatibility_date = "2024-12-01"

workers_dev = true

[assets]
directory = "./public"

[vars]
DOMAIN = "clawmail.dev"

[[d1_databases]]
binding = "DB"
database_name = "clawmail"
database_id = "2c80e2f0-272c-42b7-a2d1-841c8b08eb08"

[triggers]
crons = ["0 0 * * *"] # Daily at midnight UTC
