name = "shellmail"
main = "src/index.ts"
compatibility_date = "2024-12-01"

workers_dev = true

routes = [
  { pattern = "shellmail.ai/*", zone_name = "shellmail.ai" },
  { pattern = "www.shellmail.ai/*", zone_name = "shellmail.ai" }
]

[assets]
directory = "./public"

[vars]
DOMAIN = "shellmail.ai"

[[d1_databases]]
binding = "DB"
database_name = "shellmail"
database_id = "8cad35bc-7f39-43f1-a36b-2884a0d24692"

[triggers]
crons = ["0 3 * * *"] # Daily at 3am UTC
